# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-26 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171225_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='图名')),
                ('image', models.ImageField(upload_to='iamge/%Y/%m', verbose_name='背景图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间')),
            ],
            options={
                'verbose_name': '背景图',
                'verbose_name_plural': '背景图',
            },
        ),
    ]
