# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_comment_nums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='weixin.jpg', upload_to='image/%Y/%m'),
        ),
    ]
