# Generated by Django 2.2.1 on 2019-06-04 14:35

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_pid', models.IntegerField(blank=True, null=True)),
                ('cate_name', models.CharField(blank=True, max_length=30, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('create_person', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='BlogCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('post_id', models.IntegerField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('create_person', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='文章名')),
                ('content', ckeditor.fields.RichTextField()),
                ('is_hot', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('click_nums', models.IntegerField(blank=True, default=0, null=True)),
                ('fav_nums', models.IntegerField(blank=True, default=0, null=True)),
                ('add_time', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'blog_post',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(blank=True, null=True)),
                ('tag_name', models.CharField(blank=True, max_length=30, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('create_person', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
    ]
