# Generated by Django 2.2.5 on 2019-10-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191025_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
    ]
