# Generated by Django 2.2.1 on 2019-06-08 21:48

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0002_auto_20190604_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='SsrModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='名称')),
                ('create_time', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'verbose_name': '酸酸乳',
                'verbose_name_plural': '酸酸乳',
            },
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
