# Generated by Django 2.2.5 on 2019-10-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogcomment_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='is_delete',
            field=models.BooleanField(default=1),
        ),
    ]
