# Generated by Django 2.2.1 on 2019-06-26 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0003_auto_20190608_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='post_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='home.BlogPost',
                                    verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
