# Generated by Django 2.2.6 on 2019-10-28 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191025_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcollection',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='blogcollection',
            name='user_id',
        ),
        migrations.AddField(
            model_name='blogcollection',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.BlogPost', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='blogcollection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='home.BlogTag', verbose_name='标签'),
        ),
    ]
