# Generated by Django 2.2.1 on 2019-06-29 19:58

import datetime
from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0004_auto_20190626_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='email',
            field=models.EmailField(default='admin@admin.com', max_length=30, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='nick_name',
            field=models.CharField(default='admin', max_length=30, verbose_name='留言用户名'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
