# Generated by Django 2.2.1 on 2019-06-29 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0005_auto_20190629_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='user_id',
            new_name='user',
        ),
    ]
