# Generated by Django 2.2.1 on 2019-06-30 11:01

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0008_auto_20190629_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='content',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
