# Generated by Django 2.2.1 on 2019-06-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190630_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtag',
            name='post_id',
        ),
    ]
