# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180307_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
    ]
