# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 17:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_is_hot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayOnw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=300)),
                ('add_time', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '每日一句',
                'verbose_name_plural': '每日一句',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
