# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 10:22
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20180307_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='IndexAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='广告')),
                ('image', models.ImageField(max_length=200, upload_to='index/%Y/%m', verbose_name='图片')),
                ('add_time', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '网站广告',
                'verbose_name_plural': '网站广告',
            },
        ),
        migrations.CreateModel(
            name='Tell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='网站公告')),
                ('content', models.CharField(max_length=300, verbose_name='公告')),
                ('add_time', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '网站公告',
                'verbose_name_plural': '网站公告',
            },
        ),
        migrations.CreateModel(
            name='TodayOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='每日一句')),
                ('content', models.CharField(max_length=300, verbose_name='内容')),
                ('add_time', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '每日一句',
                'verbose_name_plural': '每日一句',
            },
        ),
        migrations.DeleteModel(
            name='TodayOnw',
        ),
        migrations.AddField(
            model_name='post',
            name='click_nums',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='fav_nums',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.Comment', verbose_name='评论'),
        ),
    ]
