# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20180308_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_nums',
            field=models.IntegerField(default=0, verbose_name='标签文章'),
        ),
    ]
