# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20180309_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='posts.Tag', verbose_name='标签'),
        ),
    ]
